# Site settings
title: 東京巣窟
email: luntiang.pentakulo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  新たな棲家に
  掘った穴を埋め
  縄張りを広げ
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deeeeeeekun.github.io/" # the base hostname & protocol for your site
twitter_username: deeeeeeekun
github_username:  deeeeeeekun

# Build settings
markdown: kramdown
