# Site settings
title: 東京巣窟
email: luntiang.pentakulo@gmail.com
description: >
  新たな棲家へ<br>
  掘った穴を埋め<br>
  縄張りを広げ
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deeeeeeekun.github.io/" # the base hostname & protocol for your site
twitter_username: deeeeeeekun
github_username:  deeeeeeekun

# Build settings
markdown: kramdown
