# Site settings
user: David Cruz
email: david.genesis.cruz@bizreach.co.jp
description: an engineer's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
permalink: :title
twitter_username: deeeeeeekun
github_username: deeeeeeekun
blog_title: 東京巣窟
blog_url: tokyosokutsu.wordpress.com

# Build settings
markdown: kramdown

# Language settings
defaults:
  -
    scope:
      path: "_posts/en"
    values:
      lang: "en"
  -
    scope:
      path: "_posts/jp"
    values:
      lang: "jp"

# Translation settings
t:
  en:
    title: Striking codes...
    bloglist_title: Programme
    about_title: artist profile
    footer_text: sometimes a singer, sometimes a dancer<br>always a programmer
  jp:
    title: codeを奏でて・・・
    bloglist_title: 演目
    about_title: 奏者について
    footer_text: ときにはシンガー、ときにはダンサー<br>いつでもエンジニア
