# Site settings
title: Blog
email: david.genesis.cruz@bizreach.co.jp
description: >
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deeeeeeekun.github.io/" # the base hostname & protocol for your site
twitter_username: deeeeeeekun
github_username:  deeeeeeekun

# Build settings
markdown: kramdown
